# Generated by Django 5.0 on 2023-12-11 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='transporte.persona'),
        ),
        migrations.AddField(
            model_name='asignarmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.material'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(related_name='proyectos', to='proyecto.empleado'),
        ),
        migrations.AddField(
            model_name='material',
            name='proyectos',
            field=models.ManyToManyField(through='proyecto.AsignarMaterial', to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='asignarmaterial',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyecto.tipoproyecto'),
        ),
    ]
