# Generated by Django 5.0 on 2023-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_proyecto_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignarmaterial',
            name='cantidad_enviada',
            field=models.IntegerField(null=True, verbose_name='Cantidad Enviada'),
        ),
        migrations.AlterField(
            model_name='asignarmaterial',
            name='fecha_envio',
            field=models.DateTimeField(null=True, verbose_name='Fecha Envio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('recp', 'Recepcion'), ('ctr', 'Constructor'), ('con', 'Contratista'), ('opr', 'Operador')], max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Aprobado'), (2, 'En Curso'), (3, 'Terminado'), (4, 'Cancelado')], verbose_name='estado'),
        ),
    ]
