# Generated by Django 5.0 on 2023-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_asignarmaterial_cantidad_enviada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proyectos',
            field=models.ManyToManyField(related_name='materiales', through='proyecto.AsignarMaterial', to='proyecto.proyecto'),
        ),
    ]
