# Generated by Django 5.0 on 2023-12-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_asignarmaterial_fecha_pedido'),
        ('transporte', '0002_alter_viaje_chofer_persona_rol_delete_chofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='empleados',
            field=models.ManyToManyField(related_name='proyectos', to='transporte.persona'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('puntuacion', models.FloatField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyecto.proyecto')),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
