# Generated by Django 5.0 on 2023-12-11 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=100, unique=True, verbose_name='CI')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('ciudad', models.CharField(choices=[('scz', 'Santa Cruz'), ('lp', 'La Paz'), ('cbba', 'Cochabamba'), ('or', 'Oruro'), ('pt', 'Potosi'), ('bn', 'Beni'), ('pa', 'Pando'), ('ch', 'Chuquisaca'), ('tj', 'Tarija')], max_length=4, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='transporte.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=100, verbose_name='Licencia')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha Contrato')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choferes', to='transporte.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, verbose_name='Placa')),
                ('capacidad_carga', models.FloatField(verbose_name='Capacidad Carga')),
                ('anho', models.CharField(max_length=4, verbose_name='Año')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descipcion')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='transporte.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('fecha_ejecutada', models.DateTimeField(verbose_name='Fecha Ejecutada')),
                ('estado', models.IntegerField(choices=[(1, 'Preparado'), (2, 'En curso'), (3, 'Finalizado'), (4, 'Cancelado')], verbose_name='Estado')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.chofer')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='proyecto.proyecto')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.vehiculo')),
            ],
        ),
    ]
