# Generated by Django 5.0 on 2023-12-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('recp', 'Recepcion'), ('ctr', 'Constructor'), ('con', 'Contratista'), ('opr', 'Operador')], max_length=20, null=True, verbose_name='Rol'),
        ),
        migrations.DeleteModel(
            name='Chofer',
        ),
    ]
